Repository SSU-Capstone-Aurora/CareVision-Backend, pull requests merged in 2025-03, with the labels that each got.

#195 [feat] 전체 조회 로직 커서 기반 페이지네이션 적용
  src/main/java/aurora/carevisionapiserver/domain/camera/api/AdminCameraController.java
  src/main/java/aurora/carevisionapiserver/domain/camera/api/NurseCameraController.java
  src/main/java/aurora/carevisionapiserver/domain/camera/converter/CameraConverter.java
  src/main/java/aurora/carevisionapiserver/domain/camera/domain/Video.java
  src/main/java/aurora/carevisionapiserver/domain/camera/dto/response/CameraResponse.java
  src/main/java/aurora/carevisionapiserver/domain/camera/repository/CustomCameraRepository.java
  src/main/java/aurora/carevisionapiserver/domain/camera/repository/CustomCameraRepositoryImpl.java
  src/main/java/aurora/carevisionapiserver/domain/camera/repository/CustomVideoRepository.java
  src/main/java/aurora/carevisionapiserver/domain/camera/repository/CustomVideoRepositoryImpl.java
  src/main/java/aurora/carevisionapiserver/domain/camera/repository/VideoRepository.java
  src/main/java/aurora/carevisionapiserver/domain/camera/service/CameraService.java
  src/main/java/aurora/carevisionapiserver/domain/camera/service/Impl/CameraServiceImpl.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/api/AdminNurseController.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/api/NurseController.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/converter/NurseConverter.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/domain/Nurse.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/dto/response/NurseResponse.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/repository/CustomNurseRepository.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/repository/CustomNurseRepositoryImpl.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/service/Impl/NurseServiceImpl.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/service/NurseService.java
  src/main/java/aurora/carevisionapiserver/domain/patient/api/AdminPatientController.java
  src/main/java/aurora/carevisionapiserver/domain/patient/converter/PatientConverter.java
  src/main/java/aurora/carevisionapiserver/domain/patient/domain/Patient.java
  src/main/java/aurora/carevisionapiserver/domain/patient/dto/response/PatientResponse.java
  src/main/java/aurora/carevisionapiserver/domain/patient/repository/CustomPatientRepository.java
  src/main/java/aurora/carevisionapiserver/domain/patient/repository/CustomPatientRepositoryImpl.java
  src/main/java/aurora/carevisionapiserver/domain/patient/repository/PatientRepository.java
  src/main/java/aurora/carevisionapiserver/domain/patient/service/Impl/PatientServiceImpl.java
  src/main/java/aurora/carevisionapiserver/domain/patient/service/PatientService.java
  src/main/java/aurora/carevisionapiserver/global/common/domain/Identifiable.java
  src/main/java/aurora/carevisionapiserver/global/common/dto/request/PageForCameraRequest.java
  src/main/java/aurora/carevisionapiserver/global/common/dto/request/PageRequest.java
  src/main/java/aurora/carevisionapiserver/global/common/service/PageService.java
  src/main/java/aurora/carevisionapiserver/global/common/service/impl/PageServiceImpl.java
  src/main/java/aurora/carevisionapiserver/global/util/CameraIdUtil.java
  src/test/java/aurora/carevisionapiserver/ControllerTestSupport.java
  src/test/java/aurora/carevisionapiserver/domain/camera/api/AdminCameraControllerTest.java
  src/test/java/aurora/carevisionapiserver/domain/camera/api/NurseCameraControllerTest.java
  src/test/java/aurora/carevisionapiserver/domain/camera/repository/CustomCameraRepositoryImplTest.java
  src/test/java/aurora/carevisionapiserver/domain/camera/repository/CustomVideoRepositoryImplTest.java
  src/test/java/aurora/carevisionapiserver/domain/camera/service/Impl/CameraServiceImplTest.java
  src/test/java/aurora/carevisionapiserver/domain/nurse/api/AdminNurseControllerTest.java
  src/test/java/aurora/carevisionapiserver/domain/nurse/api/NurseControllerIntegrationTest.java
  src/test/java/aurora/carevisionapiserver/domain/nurse/repository/CustomNurseRepositoryImplTest.java
  src/test/java/aurora/carevisionapiserver/domain/patient/api/AdminPatientControllerTest.java
  src/test/java/aurora/carevisionapiserver/domain/patient/repository/CustomPatientRepositoryImplTest.java
  src/test/java/aurora/carevisionapiserver/global/common/service/impl/PageServiceImplTest.java
  src/test/java/aurora/carevisionapiserver/global/util/CameraIdUtilTest.java
Labels: feat

#199 [feat] 카메라 조회할때 필요한 마지막 인덱스 값 조회 기능 구현
  src/main/java/aurora/carevisionapiserver/domain/camera/service/Impl/CameraServiceImpl.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/service/Impl/NurseServiceImpl.java
  src/main/java/aurora/carevisionapiserver/domain/patient/service/Impl/PatientServiceImpl.java
  src/main/java/aurora/carevisionapiserver/global/common/dto/request/BasePageRequest.java
  src/main/java/aurora/carevisionapiserver/global/common/dto/request/PageForCameraRequest.java
  src/main/java/aurora/carevisionapiserver/global/common/dto/request/PageRequest.java
  src/main/java/aurora/carevisionapiserver/global/common/service/impl/PageServiceImpl.java
  src/test/java/aurora/carevisionapiserver/global/common/dto/request/PageForCameraRequestTest.java
  src/test/java/aurora/carevisionapiserver/global/common/dto/request/PageRequestTest.java
  src/test/java/aurora/carevisionapiserver/global/common/service/impl/PageServiceImplTest.java
Labels: feat

#197 [feat] Elasticsearch와 DB 동기화 API 작성 및 인덱스 매핑 셸 스크립트 작성
  scripts/init_elasticsearch.sh
  src/main/java/aurora/carevisionapiserver/domain/nurse/converter/NurseDocumentConverter.java
  src/main/java/aurora/carevisionapiserver/global/config/SecurityConfig.java
  src/main/java/aurora/carevisionapiserver/global/elasticsearch/api/ElasticSearchSyncController.java
  src/main/java/aurora/carevisionapiserver/global/elasticsearch/service/ElasticSearchSyncService.java
  src/main/java/aurora/carevisionapiserver/global/elasticsearch/service/Impl/ElasticSearchSyncSyncServiceImpl.java
  src/main/resources/elasticsearch/nurse-mapping.json
  src/main/resources/elasticsearch/patient-mapping.json
  src/test/java/aurora/carevisionapiserver/global/elasticsearch/service/ElasticSearchSyncServiceTest.java
Labels: feat

#201 [feat] 담당 환자 등록 및 연결 기능 개선, 결합도 감소와 멀티스레드 테스트 추가
  src/main/java/aurora/carevisionapiserver/domain/camera/dto/request/CameraRequest.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/api/NurseController.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/domain/Nurse.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/service/Impl/NurseServiceImpl.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/service/NurseService.java
  src/main/java/aurora/carevisionapiserver/domain/patient/api/AdminPatientController.java
  src/main/java/aurora/carevisionapiserver/domain/patient/dto/request/PatientRequest.java
  src/main/java/aurora/carevisionapiserver/domain/patient/service/Impl/PatientServiceImpl.java
  src/main/java/aurora/carevisionapiserver/domain/patient/service/PatientRegistrationService.java
  src/main/java/aurora/carevisionapiserver/domain/patient/service/PatientService.java
  src/main/java/aurora/carevisionapiserver/global/common/service/ConnectService.java
  src/main/java/aurora/carevisionapiserver/global/common/service/impl/ConnectServiceImpl.java
  src/test/java/aurora/carevisionapiserver/ControllerTestSupport.java
  src/test/java/aurora/carevisionapiserver/domain/nurse/api/NurseControllerTest.java
  src/test/java/aurora/carevisionapiserver/domain/patient/service/Impl/PatientServiceImplConcurrencyTest.java
  src/test/java/aurora/carevisionapiserver/domain/patient/service/PatientRegistrationServiceConcurrencyTest.java
  src/test/java/aurora/carevisionapiserver/global/common/service/impl/ConnectServiceImplTest.java
Labels: feat, test

#203 [refactor] 카메라 정렬 조건을 카메라 아이디에서 bed로 변경
  src/main/java/aurora/carevisionapiserver/domain/bed/repository/BedRepository.java
  src/main/java/aurora/carevisionapiserver/domain/bed/repository/CustomBedRepository.java
  src/main/java/aurora/carevisionapiserver/domain/bed/repository/impl/CustomBedRepositoryImpl.java
  src/main/java/aurora/carevisionapiserver/domain/bed/service/BedService.java
  src/main/java/aurora/carevisionapiserver/domain/bed/service/impl/BedServiceImpl.java
  src/main/java/aurora/carevisionapiserver/domain/camera/repository/CameraRepository.java
  src/main/java/aurora/carevisionapiserver/domain/camera/repository/CustomCameraRepository.java
  src/main/java/aurora/carevisionapiserver/domain/camera/repository/CustomCameraRepositoryImpl.java
  src/main/java/aurora/carevisionapiserver/domain/camera/service/Impl/CameraServiceImpl.java
  src/test/java/aurora/carevisionapiserver/domain/bed/repository/CustomBedRepositoryTest.java
  src/test/java/aurora/carevisionapiserver/domain/camera/repository/CustomCameraRepositoryImplTest.java
  src/test/java/aurora/carevisionapiserver/domain/camera/repository/CustomVideoRepositoryTest.java
  src/test/java/aurora/carevisionapiserver/domain/camera/service/CameraServiceTest.java
  src/test/java/aurora/carevisionapiserver/domain/nurse/repository/CustomNurseRepositoryTest.java
  src/test/java/aurora/carevisionapiserver/domain/patient/repository/CustomPatientRepositoryTest.java
  src/test/java/aurora/carevisionapiserver/global/common/service/PageServiceTest.java
Labels: feat, refactor

#206 [refactor] DTO에서 요청 파라미터로 페이지 처리 값 입력 받도록 수정
  src/main/java/aurora/carevisionapiserver/domain/camera/api/AdminCameraController.java
  src/main/java/aurora/carevisionapiserver/domain/camera/api/NurseCameraController.java
  src/main/java/aurora/carevisionapiserver/domain/camera/repository/CameraRepository.java
  src/main/java/aurora/carevisionapiserver/domain/camera/service/CameraService.java
  src/main/java/aurora/carevisionapiserver/domain/camera/service/Impl/CameraServiceImpl.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/api/AdminNurseController.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/api/NurseController.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/service/Impl/NurseServiceImpl.java
  src/main/java/aurora/carevisionapiserver/domain/nurse/service/NurseService.java
  src/main/java/aurora/carevisionapiserver/domain/patient/api/AdminPatientController.java
  src/main/java/aurora/carevisionapiserver/domain/patient/service/Impl/PatientServiceImpl.java
  src/main/java/aurora/carevisionapiserver/domain/patient/service/PatientService.java
  src/test/java/aurora/carevisionapiserver/domain/camera/api/AdminCameraControllerTest.java
  src/test/java/aurora/carevisionapiserver/domain/camera/api/NurseCameraControllerTest.java
  src/test/java/aurora/carevisionapiserver/domain/camera/service/CameraServiceTest.java
  src/test/java/aurora/carevisionapiserver/domain/nurse/api/AdminNurseControllerTest.java
  src/test/java/aurora/carevisionapiserver/domain/nurse/api/NurseControllerIntegrationTest.java
  src/test/java/aurora/carevisionapiserver/domain/patient/api/AdminPatientControllerTest.java
  src/test/java/aurora/carevisionapiserver/domain/patient/service/PatientServiceConcurrencyTest.java
  src/test/java/aurora/carevisionapiserver/global/common/service/ConnectServiceTest.java
Labels: refactor

#209 [refactor] 카메라 조회시 N+1 문제 해결을 위해 fetch join 적용
  src/main/java/aurora/carevisionapiserver/domain/bed/repository/impl/CustomBedRepositoryImpl.java
  src/main/java/aurora/carevisionapiserver/domain/camera/service/Impl/CameraServiceImpl.java
Labels: fix, refactor
